### ISSUE TITLE
Expose the response mappers

### ISSUE THREAD

**Issue by sitch** [wfgilman/plaid-elixir#17]
Currently `Plaid.Utils.map_body/2` is privately defined, but this can be useful externally to libs.  For instance, implementing an `Ecto.Type` behaviour.

This parsing functionality could be safely moved into its own module and called from `Plaid.Utils.handle_resp/2` to maintain the existing public signature.

Moving this to somewhere like `Plaid.Middlewares.ResponseHandler` makes a lot of sense to me.

**Comment by wfgilman** [comment]
How would you imagine an external lib using the response mapper?

**Comment by sitch** [comment]
This is not my **exact** usecase but it demonstrates a usecase
```elixir
defmodule MyApp.EctoPlaidTransactions do
  @behaviour Ecto.Type
  
  def type, do: :map

  def cast(%Plaid.Transactions{} = plaid_transactions) do
    {:ok, plaid_transactions}
  end

  def cast(plaid_transactions) when is_map(plaid_transactions) do
    # This is a bit hacky due to an unnecessary transform
    with {:ok, plaid_transactions_binary} <- dump(plaid_transactions) do
      cast(plaid_transactions_binary)
    else
      _ -> :error
    end
  end

  def cast(plaid_transactions) when is_binary(plaid_transactions) do
    # Currently `.map_body/2` is private though
    Plaid.Utils.map_body(plaid_transactions, :transactions)
  end

  def dump(%Plaid.Transactions{} = plaid_transactions) do
    Poison.encode(plaid_transactions)
  end
end
```

**Comment by wfgilman** [comment]
Gotcha. Yeah I can do that.

**Comment by wfgilman** [comment]
@sitch would this PR address your issue?

**Comment by sitch** [comment]
Yes sir! Very thanks 👍
