### ISSUE TITLE
Calls still require creds to be set via config

### ISSUE THREAD

**Issue by jc00ke** [wfgilman/plaid-elixir#25]
I just tried out #24 and functions like [Plaid.Accounts.get/2](https://github.com/wfgilman/plaid-elixir/commit/b8913db2988a7cacaebda09023420cd8e2380120#diff-779933877eb2eb7e9795b0e356a30145R79) still call `get_cred/0` which raises if `public_key, client_id & secret` are not set in the application config for `:plaid`.

I put in some `"N/A"` for now, which is getting me by, but ideally I wouldn't have to set those at all.

**Comment by wfgilman** [comment]
Ah, you'd like the config to be entirely runtime if the user wants it. Okay, should be an easy tweak.

**Comment by wfgilman** [comment]
I created the following PR which should take care of your workaround. Want to give it a test drive before I merge it? https://github.com/wfgilman/plaid-elixir/pull/28/files

**Comment by jc00ke** [comment]
Sweet, I'll try to give it a whirl this afternoon. Looks good on first review.

**Comment by wfgilman** [comment]
Fixed by https://github.com/wfgilman/plaid-elixir/pull/28
