### ISSUE TITLE
Plaid won't ignore pk if sent

### ISSUE THREAD

**Issue by jc00ke** [wfgilman/plaid-elixir#26]
![image](https://user-images.githubusercontent.com/18191/58041434-f0109580-7aec-11e9-80c9-affb773ee24b.png)
Very particular.

According to the docs, `public_key` is required for:
```
POST /institutions/search
POST /institutions/get_by_id
```
and it's apparently now allowed for any other call. This affects the dynamic config where I'm just passing everything in.

**Comment by wfgilman** [comment]
Ah, so you’d like to be able to pass in the entire config map and have the
functions only use the applicable ones. I can have them strip out the
credentials that don’t make sense for the endpoint.

That’s helpful context.

**Comment by jc00ke** [comment]
That'd be nice. Thank you!

**Comment by wfgilman** [comment]
This is fixed by https://github.com/wfgilman/plaid-elixir/commit/9121a6b2f543e9e37c2f1be29184f670c56cc78b. I want to build out the tests more to make sure the behavior is expected.
