### ISSUE TITLE
Support for Plaid Identity

### ISSUE THREAD

**Issue by churcho** [wfgilman/plaid-elixir#36]
Is there any reason why this is not implemented so far? Seems like it conforms to what already exists in terms of architecture and fetching would mean tweaking the endpoints as done in the various products, right?

Need this for a service I am working on and wanted to know what limits us from having it on this package, if any.

**Comment by wfgilman** [comment]
There just hasn't been any demand for it. I'm happy to accept a PR to support it. I'm no longer actively using Plaid for my business so I'd be developing against the documentation. I'll put it on my todo list but not sure when I'll get around to adding it.

**Comment by wfgilman** [comment]
This feature was added by @LightningK0ala 😎 in https://github.com/wfgilman/plaid-elixir/pull/39
