### ISSUE TITLE
Institutions calls not returning correct API response

### ISSUE THREAD

**Issue by ealmz** [wfgilman/plaid-elixir#41]
Hey y'all, this library is fantastic. Thank you so much. I am using
`Institutions.get()` and my response comes back with nils. I logged the following http response in `Plaid.Utils` and it came back as expected.
```
  def handle_resp({:ok, %HTTPoison.Response{status_code: code} = resp}, endpoint)
      when code in 200..201 do
    {:ok, map_response(resp.body, endpoint)}
  end
```

Any ideas on what this could be? My Plaid credentials / env vars have been no issue with the rest of this library.

**Comment by wfgilman** [comment]
Do you sort this out okay?

**Comment by ealmz** [comment]
@wfgilman thanks for the response! I did. I made the fix in my company's forked repo here: https://github.com/RiverFinancial/plaid-elixir/pull/2

Let me know if I should make a PR here as well. Would appreciate any review + suggestion on better tests.

**Comment by wfgilman** [comment]
I’d appreciate the PR! Would like to keep the library 👌 happy to review

**Comment by wfgilman** [comment]
> @wfgilman thanks for the response! I did. I made the fix in my company's forked repo here: [RiverFinancial#2](https://github.com/RiverFinancial/plaid-elixir/pull/2)
> 
> Let me know if I should make a PR here as well. Would appreciate any review + suggestion on better tests.

I finally got around to integrating this enhancement. Here's how I handled it: https://github.com/wfgilman/plaid-elixir/commit/6af11169c46ef1ea994cf7fd6a26025fc30a633f

**Comment by ealmz** [comment]
Awesome! Sorry I didn't make a PR for this.

**Comment by wfgilman** [comment]
No sweat 😎
