### ISSUE TITLE
Consent expiration time and Auth.Numbers

### ISSUE THREAD

**Issue by agramichael** [wfgilman/plaid-elixir#49]
Is there a particular reason for why the Item struct doesn't contain the `consent_expiration_time` information that Plaid's api returns?

https://plaid.com/docs/#item-schema

**Comment by agramichael** [comment]
Also noticed for the Auth.Numbers, there is ACH and EFT but no BACS or International numbers.

https://plaid.com/docs/#international-numbers-schema
https://plaid.com/docs/#bacs-numbers-schema

**Comment by wfgilman** [comment]
Hi @agramichael! Thanks for the comment. I'm maintaining the library but not actively using it - so I'm not keeping it in sync with changes to the Plaid API in real-time. I'll gladly merge a PR that keeps the library updated though.

**Comment by wfgilman** [comment]
I tacked these changes onto this PR https://github.com/wfgilman/plaid-elixir/pull/50
