### ISSUE TITLE
Support for client/secret instead of public key

### ISSUE THREAD

**Issue by ethangunderson** [wfgilman/plaid-elixir#56]
Plaid has deprecated the use of public key auth in APIs, and new accounts can't even generate a key. As best as I can tell, this means I can't use plaid-elixir to pull institution information, since it forces the existence of a configured public key.

Looking at the implementation, it appears that this could be as simple as swapping out usages of `validate_public_key` for `validate_cred`. I'm not sure what kind of backward capability you're looking to maintain though. Anything I'm missing? If not, I can start working on a PR. Thanks!

**Comment by agramichael** [comment]
Yeah it looks like `get` already uses `validate_cred` by `get_by_id` and `search` don't. 

I think swapping out usages would do the trick.

**Comment by wfgilman** [comment]
@ethangunderson would this fix your issue? https://github.com/wfgilman/plaid-elixir/tree/deprecated-public-key

**Comment by wfgilman** [comment]
Fixed by https://github.com/wfgilman/plaid-elixir/pull/58
