### ISSUE TITLE
Implement Authentication endpoint 

### ISSUE THREAD

**Issue by zacck** [wfgilman/plaid-elixir#6]
Hey, we could use your lib where I work, I was wondering if you would accept some suggestions?
Would it be ok if we could implement 
- The authentication endpoint
- Make json parse and http client configurable?

**Comment by wfgilman** [comment]
lemme know when ur ready to bump the version to include these change. I can publish it to hex

**Comment by zacck** [comment]
Hey @wfgilman  the recent merge seems to make the lib more than sufficient for me :) I think we can close this issue for now?
