### ISSUE TITLE
Plaid swag?

### ISSUE THREAD

**Issue by phoenixy1** [wfgilman/plaid-elixir#64]
Hi @wfgilman -- sorry for opening an issue but I don't have a better way to get in touch with you.

Anyway, I'm on the Developer Relations team at Plaid and I just wanted to say thanks for your work maintaining this library.

As a thank-you we'd like to send you a small Plaid care package. If you're interested, can you let me know your shipping address, t-shirt size, and if there are any items you'd particularly like?  You can DM me on Twitter at @plaiddev or email ahoffer@plaid.com.

Thanks,
Alex

P.S. If you haven't already seen it, you might be interested in our newly-published OpenAPI file at https://github.com/plaid/plaid-openapi, which is designed to make Plaid SDK generation easier -- we'd love to hear any feedback you might have!

**Comment by wfgilman** [comment]
Hi @phoenixy1  - just sent you an email 🙂
