### ISSUE TITLE
Telemetry events around http requests

### ISSUE THREAD

**Issue by kanes115** [wfgilman/plaid-elixir#68]
Hey,

we've been using this library for some time now and now we came across a need for putting some metrics around HTTP calls our system makes. We've been thinking of adding some telemetry events emitting to Plaid library itself to allow anybody using it handle them and later report. Our suggestions would be to have a set of events similar to this:
* plaid.request.start (measurement: `system_time`)
* plaid.request.stop (measurement: `duration`)
* plaid.request.exception (measurement: `duration`)
All of them would have metadata containing basic request info (path, status code, url etc.).

We're happy to implement it ourselves, let us know what you think.

**Comment by wfgilman** [comment]
I'm all for it. The biggest change I can see is that it might necessitate an `application.ex` to attach telemetry events to their handlers. Right now the library is just bindings.

I'd love to see your implementation and work on getting it integrated into the library.
