### ISSUE TITLE
Improve testing suite by adding Mox

### ISSUE THREAD

**Issue by wfgilman** [wfgilman/plaid-elixir#72]
Restructure test suite to decouple the business logic from the HTTP client.

**Comment by wfgilman** [comment]
Addressing this issue in this branch https://github.com/wfgilman/plaid-elixir/tree/mox-test-suite

**Comment by yordis** [comment]
@wfgilman related to `mox-test-suite` I would suggest changing the API and following good practices for libraries https://hexdocs.pm/elixir/main/library-guidelines.html#avoid-application-configuration

Pass the client as the first parameter of all the functions. Now with `Kernel.then` makes it is even easier to reposition the parameter.

**Comment by wfgilman** [comment]
Thanks for the suggestion, @yordis. I'm incorporating it into the enhancements I'm making to the test suite in this branch.

**Comment by yordis** [comment]
I have a local version that I would like to delete from my app, here is what I have so far:

I am thinking of codegen the client rather than maintaining it manually.

```elixir
defmodule Plaid.Client do
  alias Plaid.Client
  alias Plaid.Client.Request

  def new do
    Tesla.client([
      {Tesla.Middleware.BaseUrl, base_url()},
      {Tesla.Middleware.Headers,
       [
         {"user-agent", "Elixir-SDK"},
         {"Plaid-Version", "2020-09-14"}
       ]},
      Tesla.Middleware.JSON
    ])
  end

  def send_request(request, client) do
    request
    |> add_auth_body()
    |> Request.to_keyword()
    |> then(&Tesla.request!(client, &1))
  end

  defp add_auth_body(request) do
    Request.merge_body(request, %{client_id: client_id(), secret: client_secret()})
  end

  defp client_id do
    Keyword.fetch!(app_env(), :client_id)
  end

  defp client_secret do
    Keyword.fetch!(app_env(), :client_secret)
  end

  defp base_url do
    case Keyword.fetch!(app_env(), :base_url) do
      :sandbox -> "https://sandbox.plaid.com"
      :production -> "https://production.plaid.com"
      :development -> "https://development.plaid.com"
    end
  end

  defp app_env do
    Application.get_env(:plaid_client, __MODULE__, [])
  end
end

defmodule Plaid.Client.Request do
  alias Plaid.Client.Request

  defstruct [:body, :method, :url]

  def new do
    %Request{}
  end

  def put_method(request, m) do
    Map.put(request, :method, m)
  end

  def put_url(request, u) do
    Map.put(request, :url, u)
  end

  def put_body(request, value) do
    Map.put(request, :body, value)
  end

  def merge_body(request, value) do
    request
    |> Map.get(:body)
    |> Map.merge(value)
    |> then(&Map.put(request, :body, &1))
  end

  def to_keyword(request) do
    [body: request.body, url: request.url, method: request.method]
  end
end


defmodule Plaid.Client.Api do
  alias Plaid.Client
  alias Plaid.Client.Request

  def link_token_create(client, body) do
    Request.new()
    |> Request.put_method(:post)
    |> Request.put_url("/link/token/create")
    |> Request.put_body(body)
    |> Client.send_request(client)
  end
end
```

**Comment by wfgilman** [comment]
Take a look at the PR once I finish my changes. If you have any requests for it to meet your needs I'm happy to accommodate.

**Comment by yordis** [comment]
It is a tricky one. Notice the following

```elixir
defmodule Web.Api.PlaidController do
  use Web, :controller

  alias Plaid.Client
  alias Plaid.Client.Api

  def link_token_create(conn, _params) do
    user_id =
      conn
      |> current_principal()
      |> Map.get(:identity)
      |> Map.get(:id)

    Client.new()
    |> Api.link_token_create(%{})
    |> map_to_resp(conn)
  end

  defp map_to_resp(env, conn) do
    conn
    |> put_status(env.status)
    |> json(env.body)
  end
end

```

I have full access to the raw response, so I can pipe it as a proxy to the frontend.

I rather remove all the code but I worry about the timing of getting things into this repo and having a use case like the previous one where it diverge a bit.

I am going for the route of giving more functions that transform the response into different shapes.

But looking forward for collaborating!

**Comment by wfgilman** [comment]
The bindings in this library are more tightly coupled to the specific endpoints of the Plaid API than your implementation which constructs the HTTP request on the fly. Most of the Plaid endpoints require credentials and make a similar POST request, so there's a lot of redundancy in the implementation for the `accounts`, `transactions`, `income`, etc. endpoints.

I think the value of this library is mostly in the legwork of mapping various external responses from Plaid to internal data structures along with abstracting the business logic of mapping endpoints and performing validation where it's required. It sounds like this is the direction you'd like to go. So I wonder if this below example would work for you?

```elixir
defmodule Web.Api.Controller do
   use Web, :controller

   def link_token_create(conn, _params) do
       user_id = ...

        case Plaid.Link.create_link_token(%{}) do
            {:ok, %Plaid.Link{} = resp_body} ->
                conn
                |> put_status(200)
                |> json(resp_body)
            {:error, _} ->
                conn
                |> put_status(400)
                |> json(%{message: "Failed to create Link token"})
        end
   end
end
```
You could repeat this pattern for any of the Plaid endpoints and remove your existing code.

If you'd like a little more flexibility by gaining access to the raw responses from Plaid, we could modify the `PlaidHandler.handle_response/2` to accept a parameter which skips mapping the external Plaid response to structs and just returns the raw response body from Plaid.

**Comment by yordis** [comment]
Your solution will work. Also, worth saying that I don't mind the pattern matching at all. 

My solution works for those cases when you want to proxy the response out as it is, including the HTTP status so you don't even think if it should be a 400, or 422, or whatever.

I am more than happy to conform to your proposed solution.

**Comment by wfgilman** [comment]
https://github.com/wfgilman/plaid-elixir/pull/75

**Comment by yordis** [comment]
@wfgilman would be prudent to use `tesla` since you are introducing a breaking change anyway?

It will allow using any HTTP client under the hood and the middleware is quite nice to add things like tracing (or remove it).

Just throwing some idea.

**Comment by wfgilman** [comment]
You read my mind. I was going to take a look at the HTTP adapter after I got the test suite changes done. I'll probably roll it all into one major version bump.

**Comment by yordis** [comment]
Follow the PR, I am gonna give it a try, and leave my thoughts there. It seems we are in the same wavelength

**Comment by wfgilman** [comment]
https://github.com/wfgilman/plaid-elixir/pull/76 Here's my implementation if you'd like to try it out
